Revert "[heap] Fix build on gcc"
This reverts commit 1a05fcf9e4af6ef6fd54b311c29092231eeccffb.

Reason for revert:
Needed to resolve conflict for another revert:
https://chromium-review.googlesource.com/c/v8/v8/+/6081152

Please reland if unrelated.

Original change's description:
> [heap] Fix build on gcc
>
> getting the error
> ```
> error: loop variable '<structured bindings>' creates a copy
> note: use reference type to prevent copying
> ```
>
> Bug: 379788114
> Change-Id: Ia06938826bba1a7141048e8043c072e52229a156
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6080911
> Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
> Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
> Cr-Commit-Position: refs/heads/main@{#97634}

Bug: 379788114
Change-Id: I854b7e1a67b19ca087ccfbf4d054029c3d24e4f0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6083871
Auto-Submit: Michael Achenbach <machenbach@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Michael Achenbach <machenbach@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#97645}