Fix argument order of assertEquals
This test fails when trying to upgrade ICU, but the failure message
has expected and found reversed, because the argument order is wrong:

> Error: Failure: expected <1582-01-01>, found <1/1/1582>.

Put the expected value first to fix this.

Change-Id: I06a12d2f12de0b1426ffecf3a891cc536f67da8d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6592932
Reviewed-by: Rezvan Mahdavi Hezaveh <rezvan@chromium.org>
Commit-Queue: Rezvan Mahdavi Hezaveh <rezvan@chromium.org>
Reviewed-by: Shu-yu Guo <syg@chromium.org>
Auto-Submit: Philip Jägenstedt <foolip@chromium.org>
Cr-Commit-Position: refs/heads/main@{#100598}