Fix compilation on big endian
Currently getting the following errors:
```
error: variable 'string' set but not used
unused variable 'start'
```

Bug: v8:12868
Change-Id: I9ee8a14da7d126270255558a630ffd2af3f87f15
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/3702966
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Reviewed-by: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/main@{#81134}