[runtime] Updating Arguments to RuntimeArguments
Fixing a compilation error:
'Arguments' requires template arguments

Change-Id: I6857adadea655dffdf40250f845f76bc1832b785
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2076297
Commit-Queue: Toon Verwaest <verwaest@chromium.org>
Reviewed-by: Victor Gomes <victorgomes@chromium.org>
Reviewed-by: Toon Verwaest <verwaest@chromium.org>
Cr-Commit-Position: refs/heads/master@{#66475}