[wasm-gc][fuzzer] Pass UnaryPredicate parameter by reference
Passing by copy could cause the following compilation error
on gcc by creating a new object with uninitialized destination:
```
src/zone/zone-containers.h:130:25: error: argument 1 null
where non-null expected
  if (size) memcpy(dst, src, size * sizeof(T));
```

Bug: v8:7748
Change-Id: Ib525cd4dded0bd0cabc2616663860057f5096058
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/4532963
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Commit-Queue: Matthias Liedtke <mliedtke@chromium.org>
Cr-Commit-Position: refs/heads/main@{#87679}