[torque][metagen] Fix build on unsupported platforms
PPC64/s390x do not use libclang provided by chromium under
`third_party/llvm-libclang/lib/libclang.so`.
As a result we are currently getting the following build failure:
```
OSError: /home/v8/third_party/llvm-libclang/lib/libclang.so:
cannot open shared object file: No such file or directory
```

This CL introduces `v8_metagen_libclang_so` and `v8_metagen_libclang_bindings_dir` so custom paths can be provided
using args.gn.

Bug: 531344950
Change-Id: I0a09c1c9f7bdb9f03d5bea5496041e8040282f8b
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8322487
Reviewed-by: Jakob Linke <jgruber@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
Cr-Commit-Position: refs/heads/main@{#109615}