Fix gcc debug builds
Currently getting this error:
```
error: call to non-'constexpr' function 'bool v8::internal::Is(Tagged<Union<HeadTs ...> >)
```
after changes from this CL: https://crrev.com/c/6351924

Sample code to reproduce the error on gcc:
https://godbolt.org/z/4evjbG9xW


Change-Id: Ie51a43d421d5e4485921f1ae0ccd79c0308220b0
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6368417
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Reviewed-by: Patrick Thier <pthier@chromium.org>
Cr-Commit-Position: refs/heads/main@{#99313}