Fix non-conforming braced-init-list in value_or()
value_or() is a function template that deduces its argument type.
Passing a braced-init-list {} causes deduction to fail in GCC
because {} has no type:

  wasm-shuffle-reducer.cc:576: error: no matching member function
  for call to 'value_or'
  note: candidate template ignored: couldn't infer template argument

Clang only accepted it by chance. Replace {} with uint8_t{0} to make
the type explicit.

Refs: https://eel.is/c++draft/temp.deduct.call
Refs: https://github.com/nodejs/node/pull/62572
Change-Id: I589617c78fbc1a65a3475957f846ffb87364ff28
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7726131
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Commit-Queue: Joyee Cheung <joyee@igalia.com>
Cr-Commit-Position: refs/heads/main@{#106357}