PPC/s390x: Fix debug builds with RHEL gcc toolset
Currently linking v8_hello_world causes a link failure
during a v8 debug build with the following error:
```
undefined reference to symbol '_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE14__xfer_bufptrsD1Ev@@GLIBCXX_3.4.21'
```
I've created a ticket to look into the cause but in the meantime
adding the ldflag `-lstdc++` fixes the issue:
https://bugzilla.redhat.com/show_bug.cgi?id=226818

Bug: v8:14652
Change-Id: Ie3131e8bf426018f2da147e92d6fc205783c2f2f
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5348144
Reviewed-by: Toon Verwaest <verwaest@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Cr-Commit-Position: refs/heads/main@{#92730}