Fix build with gcc12
- A number of erroneous flags have been added to BUILD.gn
- wasm-init-expr.cc is creating an 8 byte buffer witch may be
  much smaller than max size_t output. We also need to make room
  for the `f` character and the terminating null character
- inspector_protocol currently generates the following error
   ```
   error: loop variable ‘json_in’ of type ‘const std::string&’ {aka
   ‘const std::__cxx11::basic_string<char>&’} binds to a temporary
   constructed from type ‘const char* const’
   ```

Change-Id: I1139899b2664e47d01ebc44f2e972fc4c0ec212d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5331756
Reviewed-by: Matthias Liedtke <mliedtke@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Reviewed-by: Toon Verwaest <verwaest@chromium.org>
Cr-Commit-Position: refs/heads/main@{#92615}