Fix build with gcc
Pragma usages on gcc causes the following:
```
error: '#pragma' is not allowed here
```

Templates inside the class causes this:
```
error: explicit specialization in non-namespace scope
```

id() causes this:
```
error: call to non-‘constexpr’ function
```

Change-Id: I1a30b2249ff1ac172172543123d37daee6d1158e
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6802502
Reviewed-by: Victor Gomes <victorgomes@chromium.org>
Reviewed-by: Nico Hartmann <nicohartmann@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
Cr-Commit-Position: refs/heads/main@{#101711}