[torque] Add missing header for compilation
Without the added header some GCC compilers might produce this error:

error: 'ceil' is not a member of 'std'

Change-Id: I4fc784725c904adc58919a766671e37c9aca7ecb
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/2181774
Commit-Queue: Milad Farazmand <miladfar@ca.ibm.com>
Commit-Queue: Tobias Tebbi <tebbi@chromium.org>
Reviewed-by: Tobias Tebbi <tebbi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#67563}