Implement DeclaresLocals() in DebugWasmInterpreterScopeIterator
https://crrev.com/c/8461906 added the pure virtual
debug::ScopeIterator::DeclaresLocals() and implemented it in
DebugWasmScopeIterator, but not in DebugWasmInterpreterScopeIterator,
which is only compiled with V8_ENABLE_DRUMBRAKE. This breaks builds
with DrumBrake enabled (e.g. tvOS):

  error: abstract class is marked 'final' [-Werror,-Wabstract-final-class]

Return true, matching DebugWasmScopeIterator, since Wasm scopes always
report as non-empty.

Bug: 545412300
Change-Id: I2f2ec39212a2611bf8a804d2a01271dd533839d6
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8485425
Commit-Queue: Gyuyoung Kim <gyuyoung@igalia.com>
Reviewed-by: Simon Zünd <szuend@chromium.org>
Reviewed-by: Jakob Linke <jgruber@chromium.org>
Cr-Commit-Position: refs/heads/main@{#110173}