Fix regress-394119934 on s390x
This CL fixes two issues with this test;
- Getting this error after https://crrev.com/c/8193557:
```
Error: illegal value for flag --osr-from-maglev of type int
```
Using `--osr-from-maglev=4` to work around it.

- It also fails intermittently on s390x with this error:
```
Failure: expected <true> found <false>

Stack: MjsUnitAssertionError
    at assertTrue test/mjsunit/mjsunit.js 565:5
    at g          test/mjsunit/maglev/regress-394119934.js 31:3
    at            test/mjsunit/maglev/regress-394119934.js 35:1
```
Increasing the `keep_going` value to give enough time for maglev
compilation to take place.

Change-Id: I7d5ed7886c5f47a2f22121b67298244cd6510c30
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8224517
Reviewed-by: Olivier Flückiger <olivf@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
Cr-Commit-Position: refs/heads/main@{#109157}