[strings] Remove unused NewStringFromUtf8SubString
Remove Factory::NewStringFromUtf8SubString() - it seems to have been
unused since crrev.com/c/1108208.

This function's code triggers Wlifetime-safety warnings on ToT Clang,
due to potentially GC-unsafe code:

src/heap/factory.cc:983:51: error: object whose reference is captured
does not live long enough [-Werror,-Wlifetime-safety-use-after-scope]
  983 |         base::Vector<const uint8_t>(str->GetChars(no_gc) + begin, length);
      |                                                   ^~~~~
src/heap/factory.cc:984:3: note: destroyed here
  984 |   }
      |   ^
src/heap/factory.cc:985:23: note: later used here
  985 |   Utf8Decoder decoder(utf8_data);
      |                       ^~~~~~~~~

Bug: 482994758, 491707176
Change-Id: Iccde9c157c07727f57c7d5a81b1096ab0ebcbc1b
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7725867
Auto-Submit: Maksim Ivanov <emaxx@chromium.org>
Reviewed-by: Deepti Gandluri <gdeepti@chromium.org>
Commit-Queue: Maksim Ivanov <emaxx@chromium.org>
Cr-Commit-Position: refs/heads/main@{#106263}