Revert "[compiler][arm64] ISel EmitShuffle4"
This reverts commit 9b369f97c824958e7c821c1f0fccaebe0a7562f0.

Reason for revert: breaks the build on Windows
error: comparison of integers of different signs: 'const unsigned int' and 'const int' [-Werror,-Wsign-compare]
../../test/unittests/compiler/arm64/turboshaft-instruction-selector-arm64-unittest.cc(3906,3): note: in instantiation of function template specialization 'testing::internal::EqHelper::Compare<unsigned int, int, nullptr>' requested here
 3906 |   EXPECT_EQ(expected_imm0, s.ToInt32(s[start]->InputAt(0)));

Failure Link: https://logs.chromium.org/logs/v8/buildbucket/cr-buildbucket/8669973271181835489/+/u/build/compile/stdout

Original change's description:
> [compiler][arm64] ISel EmitShuffle4
>
> Move the functionality out of the code generator and also support
> i8 and i16 elements, instead of just i32. The functionality has
> changed a bit because we now also decide to use a TBL when the inputs
> are the same and there's no duplicate lane.
>
> Change-Id: If04d53805531b9612fd262eb5d27c3a87df8b2b6
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8425102
> Reviewed-by: Thibaud Michaud <thibaudm@chromium.org>
> Commit-Queue: Sam Parker-Haynes <sam.parker@arm.com>
> Cr-Commit-Position: refs/heads/main@{#109990}

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Idb0c6450e840932ef0562b9e5474e43d283831f5
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8439797
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Jakob Kummerow <jkummerow@chromium.org>
Auto-Submit: Jakob Kummerow <jkummerow@chromium.org>
Cr-Commit-Position: refs/heads/main@{#109994}