Revert "[turboshaft] initialize constant_value_ to an empty value"
This reverts commit f6bef09b3b0a4aedaa59ff86a33c9f1d7427357b.

Reason for revert: fails on https://ci.chromium.org/ui/p/v8/builders/ci/V8%20Blink%20Linux/30587/overview

Original change's description:
> [turboshaft] initialize constant_value_ to an empty value
>
> gcc-10 seems to have a bug were not initializing this value
> throws this compilation error:
> ```
> src/compiler/turboshaft/assembler.h:680:16: error: ‘<anonymous>’ is used uninitialized in this function [-Werror=uninitialized]
>   680 |     return Get();
> ```
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86465
>
> Bug: v8:12783
> Change-Id: I7a5fee5009b866a801326fba734c156c3cfdb1b0
> Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5503350
> Reviewed-by: Nico Hartmann <nicohartmann@chromium.org>
> Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
> Cr-Commit-Position: refs/heads/main@{#93675}

Bug: v8:12783
Change-Id: I94ef79bd92811803e1581ec0c47daffc1bb11aa1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5509655
Owners-Override: Eva Herencsárová <evih@chromium.org>
Reviewed-by: Eva Herencsárová <evih@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Eva Herencsárová <evih@chromium.org>
Cr-Commit-Position: refs/heads/main@{#93676}