s390: use %r15 instead of %sp
Some compilers do not recognize %sp and output:
```
error: invalid register
```

Change-Id: I2e1b64dd0e799a03afccbd12f5b2db17b3130e07
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/6603554
Reviewed-by: Michael Lippautz <mlippautz@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@redhat.com>
Reviewed-by: Junliang Yan <junyan@redhat.com>
Cr-Commit-Position: refs/heads/main@{#100576}