Fix build with clang on big endian
Clang currently generates the following warning/error due to
`UNIMPLEMENTED();` being used above them:
```
error: code will never be executed
```

Change-Id: I1cd8400ec1af66cfc15a089a50548275b3d0365b
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7080049
Reviewed-by: Jakob Linke <jgruber@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
Cr-Commit-Position: refs/heads/main@{#103341}