[test] Fix WaitUntilBlocked arg cnt in regress-519664497
Fix the following error:

test/mjsunit/compiler/regress-519664497.js:29: SyntaxError: Runtime
function given wrong number of arguments
  %WaitUntilBlocked('NewConsString');
                                   ^
  SyntaxError: Runtime function given wrong number of arguments

In the test added in crrev.com/c/7956057, the %WaitUntilBlocked call
lacks the second parameter, which was made mandatory in the
concurrently-CQ'ed crrev.com/c/7957840.

Bug: 519664497, 514998642
Change-Id: I2e292c5bedcf8aaaca4f425b8c3ebb814a297c7d
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7965517
Commit-Queue: Andreas Haas <ahaas@chromium.org>
Auto-Submit: Maksim Ivanov <emaxx@google.com>
Reviewed-by: Andreas Haas <ahaas@chromium.org>
Reviewed-by: Marja Hölttä <marja@chromium.org>
Cr-Commit-Position: refs/heads/main@{#108099}