Update V8 DEPS (trusted)
Manual change: Not Rolling third_party/instrumented_libs!
Planned:
https://chromium.googlesource.com/chromium/third_party/instrumented_libraries/+log/0172d67..f75a3f1
This caused errors with `checkout_instrumented_libraries`:
  File "[...]/v8/depot_tools/gclient_eval.py", line 643, in _convert
    raise ValueError('invalid "and" operand %r (inside %r)' %
ValueError: invalid "and" operand 'non_git_source' (inside '(checkout_instrumented_libraries and non_git_source) and (checkout_instrumented_libraries)')

Rolling build: https://chromium.googlesource.com/chromium/src/build/+log/d273a5a..5ecb9a9

Rolling third_party/catapult: https://chromium.googlesource.com/catapult/+log/ec40c25..24a969a

Rolling third_party/depot_tools: https://chromium.googlesource.com/chromium/tools/depot_tools/+log/09c232e..97246c4

Rolling third_party/googletest/src: https://chromium.googlesource.com/external/github.com/google/googletest/+log/9b4993c..305e5a2

Rolling third_party/libc++abi/src: https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libcxxabi/+log/5067b87..b663b9c

Rolling third_party/libunwind/src: https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libunwind/+log/e0a4f35..8c5b971

Rolling tools/clang: https://chromium.googlesource.com/chromium/src/tools/clang/+log/9772a0a..7d6eb60

Roll created at https://cr-buildbucket.appspot.com/build/8746726292535774945

Change-Id: Ic10c09d5bf19a049030b14cdf2e4ce5fd57c11c7
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/5572657
Commit-Queue: Matthias Liedtke <mliedtke@chromium.org>
Reviewed-by: Eva Herencsárová <evih@chromium.org>
Cr-Commit-Position: refs/heads/main@{#94132}