[wasm] Make LimitsByte::is_shared() work in GCC
Importing a shared WebAssembly memory currently fails under gcc with

LinkError: ...mismatch in shared state of memory, declared = 0,
imported = 1

Since SharedFlag is `enum class : bool`, due to
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96496, gcc currently
incorrectly truncates the integer instead of converting it into
boolean, so 0x3 ends up being converted to SharedFlag::kNo.
This patch works around it with an explicit conversion.

Change-Id: I426e578513b721888076c64616d2486ccae9e12a
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/7867245
Reviewed-by: Manos Koukoutos <manoskouk@chromium.org>
Commit-Queue: Joyee Cheung <joyee@igalia.com>
Cr-Commit-Position: refs/heads/main@{#107524}